import ContractPreview from '../components/ContractPreview';

export default function PreviewSection() {
  return (
    <div className="bg-white rounded-2xl border border-black/5 overflow-hidden mb-6">
      <div className="p-5 sm:p-6 border-b border-black/5">
        <h2 className="font-display font-bold text-base text-black mb-1">Contract Preview</h2>
        <p className="text-xs text-black/50">
          Sample international trade agreement — fields will be dynamically generated by AI once the platform is live.
        </p>
      </div>
      <div className="p-4 sm:p-5">
        <ContractPreview />
      </div>
    </div>
  );
}
